[package]
name = "merdadopago"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = "0.11"
oauth2 = "4.4"
thiserror = "1.0"

[dev-dependencies]
tokio = {version = "1.32", features = ["full"]}
dotenvy = "0.15"