[package]
name = "mpago"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = {version = "1.0", features = ["derive"]}
thiserror = "1.0"

[dev-dependencies]
tokio = {version = "1.32", features = ["full"]}
dotenvy = "0.15"
